# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"

server:
  build:
    context: .
    dockerfile: Dockerfile
  # environment:
  #   DATABASE_URL: ${DATABASE_URL}
  depends_on:
    - postgres
  command: >
    sh -c "npx prisma migrate deploy &&
           npm start"
  ports:
    - "3000:3000"
